# Generated by Django 2.1.2 on 2018-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Link_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('running_seq', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Link_Master',
            fields=[
                ('link_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('module_path', models.CharField(max_length=300)),
                ('module_function', models.CharField(max_length=100, null=True)),
                ('module_input', models.CharField(max_length=100, null=True)),
                ('module_output', models.CharField(max_length=100, null=True)),
                ('select_pre_module_output', models.CharField(max_length=100, null=True)),
                ('using_pre_prediction', models.BooleanField(default=False)),
                ('pre_process_group', models.CharField(max_length=100, null=True)),
                ('pre_process_name', models.CharField(max_length=100, null=True)),
                ('pre_process_argument_json', models.TextField(default='')),
                ('post_process_group', models.CharField(max_length=100, null=True)),
                ('post_process_name', models.CharField(max_length=100, null=True)),
                ('post_process_argument_json', models.TextField(default='')),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Util_Mgmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('process_name', models.CharField(max_length=100)),
                ('module_path', models.CharField(max_length=300, null=True)),
                ('module_function', models.CharField(max_length=100, null=True)),
                ('argument_json', models.TextField(default='')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='util_mgmt',
            unique_together={('group_name', 'process_name')},
        ),
        migrations.AlterUniqueTogether(
            name='model_master',
            unique_together={('model_name', 'module_path')},
        ),
        migrations.AlterUniqueTogether(
            name='model_link_detail',
            unique_together={('link_name', 'model_name', 'running_seq')},
        ),
    ]
