# Generated by Django 2.1a1 on 2018-07-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeLinkDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('running_seq', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModeLinkMaster',
            fields=[
                ('link_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('module_path', models.CharField(max_length=300)),
                ('module_function', models.CharField(max_length=100, null=True)),
                ('module_input', models.CharField(max_length=100, null=True)),
                ('module_output', models.CharField(max_length=100, null=True)),
                ('select_pre_module_output', models.CharField(max_length=100, null=True)),
                ('using_pre_prediction', models.BooleanField(default=False)),
                ('pre_process_group', models.CharField(max_length=100, null=True)),
                ('pre_process_name', models.CharField(max_length=100, null=True)),
                ('pre_process_argument_json', models.TextField(default='')),
                ('post_process_group', models.CharField(max_length=100, null=True)),
                ('post_process_name', models.CharField(max_length=100, null=True)),
                ('post_process_argument_json', models.TextField(default='')),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilMgmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('process_name', models.CharField(max_length=100)),
                ('module_path', models.CharField(max_length=300, null=True)),
                ('module_function', models.CharField(max_length=100, null=True)),
                ('argument_json', models.TextField(default='')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='utilmgmt',
            unique_together={('group_name', 'process_name')},
        ),
        migrations.AlterUniqueTogether(
            name='modelmaster',
            unique_together={('model_name', 'module_path')},
        ),
        migrations.AlterUniqueTogether(
            name='modelinkdetail',
            unique_together={('link_name', 'model_name', 'running_seq')},
        ),
    ]
